#!/usr/bin/env sh

DIR="${DIR:-$BLOCK_INSTANCE}"
DIR="${DIR:-$HOME}"

ALERT_LOW="${ALERT_LOW:-$1}"
ALERT_LOW="${ALERT_LOW:-10}"

LOCAL_FLAG="-l"
if [ "$1" = "-n" ] || [ "$2" = "-n" ]; then
    LOCAL_FLAG=""
fi

df -h -P $LOCAL_FLAG "$DIR" | awk -v label="$LABEL" -v alert_low=$ALERT_LOW '
/\/.*/ {
    print label $4
    print label $4

    use=$5

    exit 0
}

END {
    gsub(/%$/, "", use)

    if(100 - use < alert_low) {
        print "#ff0000"
    }
}
'
