#!/bin/sh

if [ "$1" = "-w" ]; then
    echo "$2" > ~/.message.rc
    exit 0
fi

if [ "$1" = "-r" ]; then
    cat ~/.message.rc
    exit 0
fi

if [ "$1" = "-c" ]; then
    echo "" > ~/.message.rc
    exit 0
fi

exit 1
